version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      backend:
        aliases:
          - postgres
    restart: unless-stopped

  supplier:
    container_name: supplier
    image: supplier:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "supplier"
    depends_on:
      - postgres
      - reports
    restart: unless-stopped

  reports:
    container_name: reports
    image: reports:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    networks:
      backend:
        aliases:
          - "reports"
    depends_on:
      - postgres
      - filestorage
    restart: unless-stopped

  gateway:
    container_name: gateway
    image: gateway:latest
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "gateway"
    restart: unless-stopped

  filestorage:
    container_name: filestorage
    image: filestorage:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    networks:
      backend:
        aliases:
          - "filestorage"
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: kondrashin
      MINIO_ROOT_PASSWORD: kondrashin123
    volumes:
      - minio:/data
    networks:
      backend:
        aliases:
          - "minio"

networks:
  postgres:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local
  supplier:
  reports:
  gateway:
  filestorage:
  minio:
