server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: supplier
          uri: http://supplier:8081
          predicates:
            - Path=/supplier/**
          filters:
            - RewritePath=/supplier/(?<path>.*), /$\{path}

#        - id: reports
#          uri: http://reports:8082
#          predicates:
#            - Path=/reports/**
#          filters:
#            - RewritePath=/reports/(?<path>.*), /$\{path}