server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: supplier
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres:5432/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 120800KB
      max-request-size: 150000KB
  output:
    ansi:
      enabled: always

reports:
  client:
    url: http://localhost:8082/reports/